### ISSUE TITLE
Realtek 8812bu Dual band USB wifi adapter support

### ISSUE THREAD

**Issue by wildlove38** [BlissRoms-x86/support#2]
Please add Realtek 8812BU dual band wifi drivers in Bliss OS.

**Comment by hmtheboy154** [comment]
I can provide support if you are willing to test

**Comment by rokejulianlockhart** [comment]
I'm really apologetic to leave a comment here, but I can't create an issue as the readme.md describes – solely external links exist:

![image](https://user-images.githubusercontent.com/42837531/208179245-daed7073-48d3-4a2f-b454-a8dbdc500a30.png)

**Comment by hmtheboy154** [comment]
how about reporting it on our Discord/Telegram ?

**Comment by rokejulianlockhart** [comment]
@hmtheboy154, that would be a lot more difficult to manage. Imagine if every developer I spoke to asked me to do that. Surely to know well the benefits of a proper bug-reporting system, as a developer yourself of a complex project?

**Comment by hmtheboy154** [comment]
> Imagine if every developer I spoke to asked me to do that. Surely to know well the benefits of a proper bug-reporting system, as a developer yourself of a complex project?

you seek for help in porting, not filing a bug so make an issue here or ask it on Discord/Telegram is the same.

> [Although I've asked a relevant question](https://discord.com/channels/795625509575720980/795629938506072065/1053405922317303940) via your Discord, it was promptly ignored.

I don't ignore you, you just impatent.

**Comment by rokejulianlockhart** [comment]
@hmtheboy154, I do not want to port it yet, but I've not nearly the technical ability to yet.

Rather, I merely want to know whether it is available, and if not, suggest that it be ported due to the significant user-base of such devices. However, I've been provided a repository to submit it to, so you needn't concern yourself with this anymore.

I am thankful for the assistance, although I must clarify that I do not believe that I was not impatient: rather, I had not considered that the helpful participants of that group would bother to look back at the chat logs and assist me, yet they did. It was truly a first for me.
