### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by ghost** [BlissRoms-x86/support#83]

**Comment by Quackdoc** [comment]
This are currently not viable options, Bliss has high storage and bandwidth requirements. Having proper direct download support is essential too. Google drive, Mega, and Dropbox all have limitations that make it unsuitable. As for torrents, a paid host would still be necessary due to bandwidth and storage constraints.

**Comment by B1Q** [comment]
> This are currently not viable options, Bliss has high storage and bandwidth requirements. Having proper direct download support is essential too. Google drive, Mega, and Dropbox all have limitations that make it unsuitable. As for torrents, a paid host would still be necessary due to bandwidth and storage constraints.

cmon man I am downloading with the speed of 56kb/s on source garbage forge with a 1gbps connection, use literally anything and it would be 1000x better than this trash website.

UPDATE: dropped to 20kb/s I fucking hate this website
