### ISSUE TITLE
🐛 [BUG] - <MaxMini-B1-Pro >

### ISSUE THREAD

**Issue by tv4you2016** [BlissRoms-x86/support#88]
### Description

I have a bmax MaxMini-B1-Pro 

- Processor | Intel® Celeronl® N3350 processor

- Graphics | Intel  HD Graphics 500

I installed the version: 

Bliss-Zenith-v16.9.6-x86_64-OFFICIAL-gapps-20240715_2

but I don't have audio, can anyone help me?

### Category

Sound

### OS Version

16.x

**Comment by electrikjesus** [comment]
Please use the documentation to troubleshoot first. 
https://docs.blissos.org/configuration/configuration-through-command-line-parameters/#audio-hal

https://docs.blissos.org/knowledgebase/troubleshooting/sound-issues

**Comment by UknowEtheG** [comment]
We don't ask for the name/model of your device because many have hardware variations between different devices. 

We ask you to determine and share: 
EXACT CPU model
EXACT GPU model

"BlissOS v16.x" is not the exact full isophile name that we ask for.  The EXACT .iso file name it's very important for us to know what you have attempted to install (as an example, we compiled several 16.9.x builds just in the past 64 hours)

You never informed anybody which installation method you have used. 

You also never shared the details of your audio card. 

As mentioned previously, We provide extensive documentation at docs.blissos.org
There are many options found in "configuring through command line parameters" and a subsection dedicated to audio options. 

The Telegram channel also has many useful notes.  When I can think of off the top of my head is called "alsa_mixer" Which is a command line utility You can launch through Termux(after granting Termux su privileges) which can be used to enable/disable different detected audio inputs and outputs. 

You can search the telegram channel You are already a member of for previous discussions related to "audio" "sound" "alsa" <~~~ use those search terms, & scroll through the search results for all relevant discussions related to the matter

**Comment by gitmanbloggus** [comment]
> We don't ask for the name/model of your device because many have hardware variations between different devices. 
> 
> We ask you to determine and share: 
> EXACT CPU model
> EXACT GPU model
> 
> "BlissOS v16.x" is not the exact full isophile name that we ask for.  The EXACT .iso file name it's very important for us to know what you have attempted to install (as an example, we compiled several 16.9.x builds just in the past 64 hours)
> 
> You never informed anybody which installation method you have used. 
> 
> You also never shared the details of your audio card. 
> 
> As mentioned previously, We provide extensive documentation at docs.blissos.org
> There are many options found in "configuring through command line parameters" and a subsection dedicated to audio options. 
> 
> The Telegram channel also has many useful notes.  When I can think of off the top of my head is called "alsa_mixer" Which is a command line utility You can launch through Termux(after granting Termux su privileges) which can be used to enable/disable different detected audio inputs and outputs. 
> 
> You can search the telegram channel You are already a member of for previous discussions related to "audio" "sound" "alsa" <~~~ use those search terms, & scroll through the search results for all relevant discussions related to the matter

I feel like it's intel audio again

**Comment by tv4you2016** [comment]
@gitmanbloggus @UknowEtheG I think so too
 Intel Audio

**Comment by UknowEtheG** [comment]
I think it is more likely that: 

Is attempting to install a Zenith build on a device with a CPU from 2016.  As reminder, Zenith builds are intended for the latest generations of hardware, utilizing a newer Linux kernel for new hardware compatibility. 

The N3350 is a dual core, single threaded processor.

Therefore, a more suitable build to install on such hardware(old, low performance) would be BlissOS v14.x GO Edition. 

v14.x for better compatibility with older hardware because of older linux kernel version
&
Based on an older version of Android which is itself lighter on system resources.

GO Edition because those are specifically intended for this situation.


@tv4you2016 
Please download and test the latest v14 GO builds using the USB installation method.
Should then return to TG for further assistance

**Comment by gitmanbloggus** [comment]
I guess? if it doesn't work then it's something with ALSA

**Comment by electrikjesus** [comment]
Please try the steps at the bottom of the audio troubleshooting doc with Intel audio issues. 
https://docs.blissos.org/knowledgebase/troubleshooting/sound-issues/#select-a-differrent-audio-hal

Thanks

**Comment by hmtheboy154** [comment]
I found this repo but it's for the Plus version. 
https://github.com/Bricker-9080/Unsupported-machines-running-linux-bmax-plus-b1-intel-n3350

It seems like to use audio here this guy have to boot with `snd-intel-dspcfg.dsp_driver=1` , meaning that forcing Legacy audio driver. Idk why it have to force like that because usually Legacy will be the default for these kind of hardware. Maybe it trying to fallback to SST or SOF but not working.

**Comment by tv4you2016** [comment]
@UknowEtheG 
I have already installed version Bliss-v14.10.3-x86_64-OFFICIAL-opengapps-20240914 using USB installation method. and continuous without audio

**Comment by UknowEtheG** [comment]
> @UknowEtheG 
> I have already installed version Bliss-v14.10.3-x86_64-OFFICIAL-opengapps-20240914 using USB installation method. and continuous without audio
> 


Excellent 
That is the build which suits your hardware correctly.  That is what you should have installed before proceeding with further troubleshooting. 

As previously mentioned, try using the legacy audio hal via command line parameter in your grub.  You can test this by turning on your device, highlighting one of the boot menu entries in grub, then type "e" to do a one-time edit, and boot to test. 
And if you wish to make the change persistent, You can then follow the documentation to edit the grub.cfg

And please, once you have the 14x go edition installation in place, return to Telegram to continue troubleshooting (That is if you are not able to help yourself with the existing documentation referenced already)

**Comment by tv4you2016** [comment]
@UknowEtheG  @hmtheboy154 @electrikjesus 
I added the command snd-intel-dspcfg.dsp_driver=1 and  AUDIO_PRIMARY=x86
 in grub and now I have:
 
 
![b92915e0-7bc3-4c30-9836-92edb6634408](https://github.com/user-attachments/assets/45bd1077-e7eb-4899-a40e-834e52f68918)

but the audio still doesn't work

I already asked on telegram but no response

**Comment by UknowEtheG** [comment]
> @UknowEtheG  @hmtheboy154 @electrikjesus 
> I added the command snd-intel-dspcfg.dsp_driver=1 and  AUDIO_PRIMARY=x86
>  in grub and now I have:
>  
>  
> ![b92915e0-7bc3-4c30-9836-92edb6634408](https://github.com/user-attachments/assets/45bd1077-e7eb-4899-a40e-834e52f68918)
> 
> but the audio still doesn't work
> 
> I already asked on telegram but no response
> 

Please do not tag me again 

Have already asked you more than once to continue this troubleshooting on Telegram 

It is a Sunday morning, nobody is paid to provide you technical support and troubleshooting.  Exercise patience and somebody will respond to you when they have a moment 

DO NOT continue to post in the bliss ROM community channel.  That is where you asked your same question about also_mixer a few hours ago.  You were then told to go to the Bliss OS Community channel.  And you did not 

I'm not going to reply to this issue anymore so please stop tagging me and go to Telegram

**Comment by gitmanbloggus** [comment]
pfff... I'm not using telegram
it's intel and their audio
